# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Nadando sobre las olas"
author:
  name: Daniel Lanza
  twitter: dalanzg
  github: dalanzg
description: "Crónicas deportivas de Daniel Lanza"
baseurl: "/nadando-sobre-las-olas" # the subpath of your site, e.g. /blog
url: "https://dalanzg.github.io" # the base hostname & protocol for your site

logo:
  path: "/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

analytics:
  google: UA-65400010-1

# Search engines
google_site_verification: CeO9J_0wi37-MvDa_F7AmZJYunwDhFGjv8eSlJFPil8
bing_webmaster: BD0D07966DC9A60772D4A70377ED337D

# Comments
comments:
  disqus: nadando-sobre-las-olas

# Build settings
paginate: 10 # the number of post per page
highlighter: rouge
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed # Possible values -> nested / expanded / compact / compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Handling Reading
exclude:
  - "README.md"
  - "LICENSE"
